languageCode = "es-ar"
title = "Esquelas"
theme = "pixess"
canonifyurls = true
baseurl = "http://martjanz.github.io/"
publishdir = "public"
layoutdir = "layouts"

[author]
	name = "Martín Anzorena"
	email = "martin.anzorena@gmail.com"
	
[params]
	twitter_username = "martianz"
